"""Human-readable startup diagnostics for the contextual runtime."""


def print_runtime_summary(args, client):
    """Print the resolved runtime contract once before accepting a simulator."""
    config = client.config
    reward = config.make_reward_config()
    print(
        "[contextual-runtime] "
        f"mode={args.mode}, action_enabled={args.action_enabled}, "
        f"reward_version={config.reward_version}, "
        f"action_mode={args.action_mode}, "
        f"dispatch_mode={config.dispatch_mode}, "
        f"action_scale={client._action_scale()}, "
        f"num_stacks={config.num_stacks}, "
        f"stack_interval={config.stack_interval}, "
        f"warmup_steps={config.warmup_steps}->{config.effective_warmup_steps}, "
        f"terminate_on_warmup_complete={config.terminate_on_warmup_complete}, "
        "state_normalizer="
        f"load:{config.load_state_normalizer_path},"
        f"save:{config.save_state_normalizer_path}, "
        f"episode_burnin_steps={config.episode_burnin_steps}, "
        f"reward_diagnostic_dir={config.reward_diagnostic_dir}, "
        f"rail_reward_mode={reward.rail_reward_mode}, "
        f"rail_free_flow_neutral_ratio={reward.rail_free_flow_neutral_ratio}, "
        f"tat_weight={reward.tat_weight}, "
        f"op_weight={reward.op_weight}, "
        f"backlog_weight={reward.backlog_weight}, "
        f"backlog_growth_weight={reward.backlog_growth_weight}, "
        f"idle_reserve_weight={reward.idle_reserve_weight}, "
        f"local_predicted_oht_weight={reward.local_predicted_oht_weight}, "
        f"local_reward_scale={reward.local_reward_scale}, "
        f"rail_tat_weight={reward.rail_tat_weight}, "
        f"rail_tat_clip={reward.rail_tat_clip}, "
        "tat_termination="
        f"{config.tat_termination_policy}:"
        f"{config.early_stop_tat_threshold:g}x"
        f"{config.tat_above_threshold_patience} after "
        f"{config.tat_termination_grace_steps}, from_episode="
        f"{config.tat_termination_start_episode}->"
        f"{config.effective_tat_termination_start_episode}, "
        f"terminal_tat_penalty={config.terminal_tat_penalty:g}, "
        f"replay_sampling={config.replay_sampling_mode}, "
        f"batch_size={config.batch_size}, "
        "resume_refill="
        f"{'full_capacity' if config.resume_inference_until_replay_full else 'minimum'},"
        f"target={config.resume_refill_target_env_steps}, "
        "resume_deterministic_first_episode="
        f"{config.resume_deterministic_first_episode}, "
        f"exploration_noise={config.exploration_noise_std}->"
        f"{min(config.exploration_noise_std, config.exploration_noise_final_std)}"
        f"@global[{config.effective_warmup_steps},"
        f"{config.effective_warmup_steps + config.exploration_noise_anneal_steps}], "
        f"seed={config.seed}, "
        f"device={client.device}"
    )
    print(
        "[contextual-runtime] rail_tat_diagnostic="
        f"{client.rail_tat_diagnostic_path}, "
        f"global_step<{config.rail_tat_diagnostic_max_step}"
    )
